### PR TITLE
Move Gigabyte R9 390 under 1002:67b1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gollux** [comment]
Hello!

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/pciutils/pciids/pull/2
> 
> -- Commit Summary --
> - Move Gigabyte R9 390 under 1002:67b1

As you can see in the README, this repository is only a mirror,
so it does not make sense to send pull requests there.

Please submit your changes via http://pci-ids.ucw.cz/.

```
            Have a nice fortnight
```

## 

Martin `MJ' Mares                          mj@ucw.cz   http://mj.ucw.cz/
Faculty of Math and Physics, Charles University, Prague, Czech Rep., Earth
"Anyone can build a fast CPU. The trick is to build a fast system." -- S. Cray

**Comment by ghost** [comment]
I am sorry. I am unable to submit the change through http://pci-ids.ucw.cz because the web interface for removing/adding PCI IDS does not make sense to me. I am suggesting that you submit the change through http://pci-ids.ucw.cz yourself, according to the contents of the patch in this pull request. Thanks.

I believe the pci.ids in this github repository is much easily readable (editable) than the web interface. Maybe you could reconsider promoting this repository to a regular change submission channel.

**Comment by gollux** [comment]
Just a note: you can also send patches to our mail robot (as mentioned on the web page).

**Comment by Firminator** [comment]
+1 for https://github.com/pciutils/pciids/pull/2#issuecomment-164421697

**Pull request closed without merging**
