### PR TITLE
Update pci.ids

### PR DESCRIPTION
**Pull request by williamcorney**
Add 1022:43bc

AMD A320 USB 3.1 XHCI Host Controller

### CODE REVIEW

**Comment by gollux** [comment]
This repository is only a mirror of the PCI ID database at  https://pci-ids.ucw.cz/. Please submit your changes there.

**Comment by williamcorney** [comment]
Hello @gollux 

I created an account at https://pci-ids.ucw.cz/ and submitted these a week ago but there has been no reply or change.

I've tried to use the robot but apparently not getting the format quite right for what it expects.

Thanks

William

**Comment by williamcorney** [comment]
@gollux 

https://admin.pci-ids.ucw.cz/read/PC/1022/43bc

**Comment by gollux** [comment]
You submitted it at the right place, but please keep in mind that review of new submissions does not happen overnight -- moderators of the database have other things to do, too. And spamming discussion every day does not help.

**Pull request closed without merging**
